services:
  postgres:
    container_name: postgres-manage-university
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: manageUniversity_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-university
    restart: unless-stopped
networks:
  spring-university:
    driver: bridge
volumes:
  postgres:
    driver: local