services:
  postgres:
    container_name: postgres-manage-university
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: manageUniversity_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-university
    restart: unless-stopped
  keycloak:
    container_name: keycloak-university
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-university
    command:
      - "start-dev"
networks:
  spring-university:
    driver: bridge
volumes:
  postgres:
    driver: local
  keycloak:
    driver: local