spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 80MB
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1
  port: 8090
